version: "3"
services:
  mysql:
    image: mysql:5.7.21
    volumes:
      - "./docker/data/mysql:/var/lib/mysql"
      - "./docker/conf/mysql:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai